config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'searches/search'
  end
  devise_for :members,skip: [:passwords],  controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
    namespace :admin do
          root to: "homes#top"
          resources :homes
          resources :cats
          resources :comment_notifications
          resources :likes
          resources :like_notifications
          resources :members
          resources :posts do
            resources :comments, only: [:destroy]
          end
        end
        
    scope module: :public do
          resources :homes
          resources :cats, only: [:new, :create, :index, :show, :edit, :update, :destroy]
          resources :comment_notifications
          resources :like_notifications
          resources :members do
                        member do
                          get :likes
                              end
                            end
          resources :posts, only: [:new, :create, :index, :show, :destroy] do
          resource :likes, only: [:create, :destroy]
          resources :comments, only: [:create, :destroy]
          end
        end
          get "/about" => "public/homes#about", as: "about"
          get "/members/my_page" => "public/members#show"
          root to: "public/homes#top"
          get '/search', to: 'public/searches#search'
          get "/members/quit" => "public/members#quit"
          get "/members/withdraw" => "public/members#withdraw"
          post "/members/withdraw" => "public/members#withdraw"
          
          devise_scope :member do
          post 'members/guest_sign_in' => 'public/sessions#guest_sign_in'
          end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  
  belongs_to :member
  has_many :posts, dependent: :destroy
  has_one_attached :cat_image
  
  validates :name, presence: true
  validates :sex, presence: true
  validates :age, presence: true
  validates :cattype, presence: true
  validates :character, presence: true
  validates :profile, presence: true
  
  
  def get_cat_image(width, height)
  unless cat_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    cat_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  cat_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :post
  has_many :comment_notifications, dependent: :destroy
  
    validates :comment, presence: true
end

app/models/comment_notification.rb
class CommentNotification < ApplicationRecord
  belongs_to :comment
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :member
  belongs_to :post
  has_many :like_notifications, dependent: :destroy
  
  validates_uniqueness_of :post_id, scope: :member_id
  
  has_many :like_notifications, dependent: :destroy 
end

app/models/like_notification.rb
class LikeNotification < ApplicationRecord
belongs_to :like


end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      #member.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      member.name = "ゲスト"
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
    has_many :cats, dependent: :destroy
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_posts, through: :likes, source: :post
    
  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end
  
  
end

app/models/post.rb
class Post < ApplicationRecord
  
    belongs_to :member
    belongs_to :cat
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_members, through: :likes, source: :member
    has_one_attached :post_image

    validates :cat_id, presence: true
    validates :post_image, presence: true
    
    
      def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    post_image.variant(resize_to_limit: [width, height]).processed
      end
      

      
end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < ApplicationController
  def show
    @cat = Cat.find(params[:id])
  end
  
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to '/admin/members'
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @members = Member.all
  end
  
end

app/controllers/admin/likes_controller.rb
class Admin::LikesController < ApplicationController
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  
  def show
    @member = Member.find(params[:id])
    @cats = @member.cats
    @posts = @member.posts
  end
  
  def index
    @members = Member.all
  end

  def edit
    @member = Member.find(params[:id])
  end
  
  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_member_path
    else
      render :edit
    end
  end

  private
    
  def member_params
    params.require(:member).permit(:id, :email, :name, :is_deleted)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to '/admin/members'
  end
        private
    
    def post_params
      params.require(:post).
      permit(:content, :tag)
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
      case resource
      when Admin
      admin_root_path
      when Member
      root_path
      end
    end
  def after_sign_up_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/cats_helper.rb
module Admin::CatsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/likes_helper.rb
module Admin::LikesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/cats/show.html.erb
ネコ詳細

<div>
  <%= image_tag @cat.get_cat_image(100,100) %>
  <p>お名前：<%= @cat.name %></p>
  <p>性別：<%= @cat.sex %></p>
  <p>年齢：<%= @cat.age %></p>
  <p>ネコの種類：<%= @cat.cattype %></p>
  <p>性格：<%= @cat.character %></p>
  <p>プロフィール：<%= @cat.profile %></p>
</div>
<td><%= link_to"Destroy",admin_cat_path(@cat), method: :delete, class:"btn btn-sm btn-danger",data: { confirm: '本当に消しますか？' } %></td>

app/views/admin/members/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-1"> 

      <h2>会員情報編集</h2>
      <%= form_with model: @member, url: admin_member_path(@member.id) do |f| %>
  
        <table>
          <div class="field text-left">
            <tr>
              <th>会員ID</th>
              <td><%= @member.id %></td>
            </tr>
            <tr>
              <th>ユーザー名</th>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td><%= f.text_field :email %></td>
            </tr>
            <tr>
              <th>会員ステータス</th>
              <td><%= f.radio_button :is_deleted, false %> 有効会員 <%= f.radio_button :is_deleted, true %> 退会済み</td>
            </tr>
          </div> 
        </table>
        <%= f.submit "変更を保存する", class:"btn btn-primary" %>
        <%= link_to :back do %>
          <button>戻る</button>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/members/index.html.erb
<p>ユーザー一覧</p>

<% @members.each do |member| %>
  <p><%= link_to admin_member_path(member.id) do %>
    <%= member.name %>
  <% end %>
  登録日<%= member.created_at.strftime('%Y/%m/%d %H:%M') %></p>
<% end %>

app/views/admin/members/show.html.erb
<div class="container">
  ユーザー詳細
  <div class="row">
    <div class="col-md-5">
      <table border="1">
        <thead>
          <tr>
            <th>ステータス</th>
            <th>ID</th>
            <th>ユーザー名</th>
            <th>メールアドレス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%if @member.is_deleted == true %>
              退会済み
              <% else %>
              有効会員
            <% end %></td>
            <td><%= @member.id %></td>
            <td><%= @member.name %></td>
            <td><%= @member.email %></td>
            <td><%= link_to "編集する", edit_admin_member_path, class:"btn btn-primary" %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-md-2">  
      <table border="1">
        <thead>
          <tr>
            <th>登録ネコ <%= @member.cats.count %> 匹</th>
            <th>ID</th>
            <th>名前</th>
          </tr>
        </thead>
        <% @cats.each do |cat| %>
          <tbody>
            <tr>
              <td><%= image_tag cat.get_cat_image(100,100) %></td>
              <td><%= cat.id %></td>
              <td><%= link_to admin_cat_path (cat.id) do %>
                <%= cat.name %>
              <% end %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <table border="1">
        <thead>
          <tr>
            <th>投稿ネコ活 <%= @member.posts.count %> 件</th>
            <th>ID</th>
            <th>ネコ</th>
            <th>タグ</th>
            <th>本文</th>
          </tr>
        </thead>
        <% @posts.each do |post| %>
          <tbody>
            <tr>
              <td><%= image_tag post.get_post_image(100,100) %></td>
              <td><%= link_to admin_post_path (post.id) do %>
                <%= post.id %>
              <% end %></td>
              <td><%= post.cat.name %></td>
              <td><%= post.tag %></td>
              <td><%= post.content.truncate(24, omission: '...') %></td><!-- truncate(文字数,オプション)←長い文字を省略するメソッド:参照https://qiita.com/ishidamakot/items/2e74d980b3a338e4c784　--> 
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
新着ネコ活一覧
<div class="container">
  <div class="row">
    <% @posts.each do |post| %>
      <span class="border border-primary">
        <div class="col-12">
          <p>投稿者:<%= post.member.name %></p>
          <p>ネコ:<%= post.cat.name %></p>
          <%= link_to admin_post_path(post.id) do %>
            <%= image_tag post.get_post_image(200,200) %>
          <% end %>
          <p><%= post.content.truncate(15, omission: '...') %></p>
          <p><%= link_to "#{post.comments.count} コメント", admin_post_path(post.id) %></p>
        </div>
      </span>
    <% end %>
  </div>
</div>

app/views/admin/posts/show.html.erb
  <table align="center" border="1">
    <thead>
      <tr>
        <th>ネコ活</th>
        <th>ID</th>
        <th>ネコ</th>
        <th>タグ</th>
        <th>いいね</th>
        <th>本文</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= image_tag @post.get_post_image(100,100) %></td>
        <td><%= @post.id %></td>
        <td><%= link_to cat_path (@post.cat.id) do %>
          <%= @post.cat.name %>
        <% end %></td>
        <td><%= @post.tag %></td>
        <td><%= @post.likes.count %></td>
        <td width="500"><%= @post.content %></td>
        <td><%= link_to"削除",admin_post_path(@post), method: :delete, class:"btn btn-sm btn-danger",data: { confirm: '本当に消しますか？' } %></td></td>
      </tr>
    </tbody>
  </table>
  
  <div align="center" ><p>コメント件数：<%= @post.comments.count %></p></div>
    <% @post.comments.each do |comment| %>
      <table align="center" border="1">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>日時</th>
            <th>コメント内容</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= link_to admin_member_path (comment.member.id) do %>
              <%= comment.member.name %>
            <% end %></td>
            <td><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></td>
            <td><%= comment.comment %></td>
            <td><%= link_to "削除", admin_post_comment_path(comment.post, comment), method: :delete, class:"btn btn-sm btn-danger",data: { confirm: '本当に消しますか？' }  %></td>
          </tr>
        </tbody>
      </table>
    <% end %>
    <div align="center"><%= link_to "戻る", action: :index %></div>