config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'searches/search'
  end
  devise_for :members,skip: [:passwords],  controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
    namespace :admin do
          root to: "homes#top"
          resources :homes
          resources :cats
          resources :comment_notifications
          resources :likes
          resources :like_notifications
          resources :members
          resources :posts do
            resources :comments, only: [:destroy]
          end
        end
        
    scope module: :public do
          resources :homes
          resources :cats, only: [:new, :create, :index, :show, :edit, :update, :destroy]
          resources :comment_notifications
          resources :like_notifications
          resources :members do
                        member do
                          get :likes
                              end
                            end
          resources :posts, only: [:new, :create, :index, :show, :destroy] do
          resource :likes, only: [:create, :destroy]
          resources :comments, only: [:create, :destroy]
          end
        end
          get "/about" => "public/homes#about", as: "about"
          get "/members/my_page" => "public/members#show"
          root to: "public/homes#top"
          get '/search', to: 'public/searches#search'
          get "/members/quit" => "public/members#quit"
          get "/members/withdraw" => "public/members#withdraw"
          post "/members/withdraw" => "public/members#withdraw"
          
          devise_scope :member do
          post 'members/guest_sign_in' => 'public/sessions#guest_sign_in'
          end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  
  belongs_to :member
  has_many :posts, dependent: :destroy
  has_one_attached :cat_image
  
  validates :name, presence: true
  validates :sex, presence: true
  validates :age, presence: true
  validates :cattype, presence: true
  validates :character, presence: true
  validates :profile, presence: true
  
  
  def get_cat_image(width, height)
  unless cat_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    cat_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  cat_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :post
  has_many :comment_notifications, dependent: :destroy
  
    validates :comment, presence: true
end

app/models/comment_notification.rb
class CommentNotification < ApplicationRecord
  belongs_to :comment
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :member
  belongs_to :post
  has_many :like_notifications, dependent: :destroy
  
  validates_uniqueness_of :post_id, scope: :member_id
  
  has_many :like_notifications, dependent: :destroy 
end

app/models/like_notification.rb
class LikeNotification < ApplicationRecord
belongs_to :like


end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      #member.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      member.name = "ゲスト"
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
    has_many :cats, dependent: :destroy
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_posts, through: :likes, source: :post
    
  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end
  
  
end

app/models/post.rb
class Post < ApplicationRecord
  
    belongs_to :member
    belongs_to :cat
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_members, through: :likes, source: :member
    has_one_attached :post_image

    validates :cat_id, presence: true
    validates :post_image, presence: true
    
    
      def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    post_image.variant(resize_to_limit: [width, height]).processed
      end
      

      
end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < ApplicationController
  def show
    @cat = Cat.find(params[:id])
  end
  
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to '/admin/members'
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @members = Member.all
  end
  
end

app/controllers/admin/likes_controller.rb
class Admin::LikesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
      case resource
      when Admin
      admin_root_path
      when Member
      root_path
      end
    end
  def after_sign_up_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/cats_helper.rb
module Admin::CatsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/likes_helper.rb
module Admin::LikesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nekomemashite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="css/smart-style.css">
    <link rel="stylesheet" href="css/pc-style.css" media="screen and (min-width: 768px)">
  </head>
  
  <body>
    <header class="shadow-sm">
      <div class="col-12", "logo_area", align="center">
        <% if admin_signed_in? %>
          <a class="navbar-brand" href="/admin"><%= image_tag 'header.jpg', class: "logo" %></a>
          <% else %>
          <a class="navbar-brand" href="/"><%= image_tag 'header.jpg', size: "350x75", class: "logo" %></a>
        <% end %>
      </div>
      <div class="col-12 mt-2 text-center">
        <% if member_signed_in? %>
          <p>ようこそ、<%= current_member.name %>さん！</p>
          <% else %>
        <% end %>
      </div>

  <div class="col-12">
      <nav class="navbar navbar-expand-xl navbar-light">
        
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse mb-2 justify-content-around" id="navbarNavDropdown">
              
                <% if member_signed_in? %>
                <div class="mt-2">
                  <%= link_to "/posts" ,class: "btn text-black btn-light", method: :get do %>
                    <i class="fas fa-paw"></i>ネコ活一覧
                  <% end %>
                </div>
         
         <div class="mt-2">
            <%= link_to "/posts/new" ,class: "btn text-black btn-light", method: :get do %>
            <i class="fas fa-pen"></i>ネコ活を投稿
            <% end %>
          </div> 

          <div class="mt-2">
            <%= link_to "/cats/new" ,class: "btn text-black btn-light", method: :get do %>
            <i class="fas fa-cat"></i>ネコを登録
            <% end %>
          </div>
          
          <div class="mt-2">
            <%= link_to "/members/my_page" ,class: "btn text-black btn-light", method: :get do %>
            <i class="fas fa-user"></i>マイページ
            <% end %>
          </div>
          
          <div class="mt-2">
            <%= link_to "/members/sign_out" ,class: "btn text-black btn-light", method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </div>
        
          <div class="d-flex mt-2">
            <%= render 'public/searches/form' %>
          </div>
        
          <% elsif admin_signed_in?%>
          <%= link_to ' ログアウト', destroy_admin_session_path, method: :delete, class:"btn btn-light" %>
          <%= link_to 'ネコ活一覧', admin_posts_path, class:"btn btn-light" %>
          <%= link_to 'ユーザー一覧', admin_members_path, class:"btn btn-light" %>
      
          <% else %>

          <ul class="navbar-nav">
            <li class="nav-item">
             <%= link_to "About", about_path, class:"btn btn-light" %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
             <%= link_to "新規登録", new_member_registration_path, class:"btn btn-light" %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
             <%= link_to "ログイン", new_member_session_path, class:"btn btn-light" %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
             <%= link_to 'ゲストログイン', members_guest_sign_in_path, method: :post, class:"btn btn-light" %>
            </li>
          </ul>
          </ul>
        <% end %>
                  
                    </div>
          
      </nav>
      </div>
    </header>
    
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer class="mt-4 py-3 bg-light sticky-bottom">
      <div class="container text-center">
        <span class="text-muted">2023 nekomemashite  &copy; All Right Reserved.</span>
      </div>
    </footer>
  </body>
</html>